#!/usr/bin/env python3

import argparse

def greet(name):
    print(f'Hello {name}!')

if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="Greet the user by name.")

    parser.add_argument('name', nargs='?', default='World', type=str, help='The name of the user (default: World)')

    args = parser.parse_args()

    greet(args.name)
